{% set name = "akismet" %}
{% set version = "1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/akismet-{{ version }}.tar.gz
  sha256: e0b5e94d5c505714f68f46a8943707e30d36b5448c7928753237715ccff192df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests

test:
  imports:
    - akismet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ubernostrum/akismet
  summary: A Python interface to the Akismet spam-filtering API.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - Admax18
